# language config, valid values:
# - zh-cn
# - en-us
lang: zh-cn
secretKeyBase: C37F5D63-EB7C-8881-2507-7C6495427830

port:
  www: 4000
  api: 4001
  account: 4002

db:
  host: 192.168.0.88
  port: 3306
  username: dev
  password: dev
  dialect: mysql
  database: app
  logging: false
  pool:
    max: 10
    min: 5
    idle: 30000
  timezone: +08:00
